# -*- coding: utf-8 -*-

from .balance import BALANCE_MAPPING
from .charges import CHARGES_MAPPING
from .customers import CUSTOMERS_MAPPING
from .disputes import DISPUTES_MAPPING
from .events import EVENTS_MAPPING
from .file_links import FILE_LINKS_MAPPING
from .files import FILES_MAPPING
from .payment_intents import PAYMENT_INTENTS_MAPPING
from .payouts import PAYOUTS_MAPPING
from .products import PRODUCTS_MAPPING
from .refunds import REFUNDS_MAPPING
from .tokens import TOKENS_MAPPING

RESOURCE_MAPPING = {}
RESOURCE_MAPPING.update(BALANCE_MAPPING)
RESOURCE_MAPPING.update(CHARGES_MAPPING)
RESOURCE_MAPPING.update(CUSTOMERS_MAPPING)
RESOURCE_MAPPING.update(DISPUTES_MAPPING)
RESOURCE_MAPPING.update(EVENTS_MAPPING)
RESOURCE_MAPPING.update(FILES_MAPPING)
RESOURCE_MAPPING.update(FILE_LINKS_MAPPING)
RESOURCE_MAPPING.update(PAYMENT_INTENTS_MAPPING)
RESOURCE_MAPPING.update(PAYOUTS_MAPPING)
RESOURCE_MAPPING.update(PRODUCTS_MAPPING)
RESOURCE_MAPPING.update(REFUNDS_MAPPING)
RESOURCE_MAPPING.update(TOKENS_MAPPING)
