# -*- coding: utf-8 -*-

from .balance import BALANCE_MAPPING
from .charges import CHARGES_MAPPING
from .customers import CUSTOMERS_MAPPING
from .disputes import DISPUTES_MAPPING
from .events import EVENTS_MAPPING
from .files import FILES_MAPPING

RESOURCE_MAPPING = {}
RESOURCE_MAPPING.update(BALANCE_MAPPING)
RESOURCE_MAPPING.update(CHARGES_MAPPING)
RESOURCE_MAPPING.update(CUSTOMERS_MAPPING)
RESOURCE_MAPPING.update(DISPUTES_MAPPING)
RESOURCE_MAPPING.update(EVENTS_MAPPING)
RESOURCE_MAPPING.update(FILES_MAPPING)
